
# xdemo: xdemo.cpp
# 	g++ -g xdemo.cpp -I ../include ../../lib/libxlib.so -o xdemo
# 	./xdemo

all: xdemo.cpp
	g++ --std=c++11 xdemo.cpp -g -I ../include ../../lib/libxlib.so -o xdemo
# 	g++ -g xdemo.cpp -I ../include ../../lib/libxlib.so -o xdemo


# run:
# 	./xdemo

clean:
	rm -f xdemo
